apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-api
  template:
    metadata:
      labels:
        app: ticket-api
    spec:
      containers:
        - name: api
          image: ticket-api:dev
          imagePullPolicy: IfNotPresent

          command:
            - uvicorn
            - app.main:app
            - --host
            - "0.0.0.0"
            - --port
            - "8000"

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://ticket:ticket@postgres:5432/ticketdb"

            - name: REDIS_URL
              value: "redis://redis:6379"

            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "redpanda:9092"

          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /livez
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"